#!/usr/bin/env python3
"""
Enterprise Subsystems Generator for Aegis Fraud Labs
Generates complete, production-grade, syntactically validated modules.
"""

import sys
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

def ensure_dir(path: Path):
    path.mkdir(parents=True, exist_ok=True)

# -------------------------------------------------------------
# 1. RULES & CEP MODULES
# -------------------------------------------------------------

def generate_rule_dsl() -> str:
    lines = []
    lines.append('"""Rule DSL Tokenizer, AST Nodes, and Recursive-Descent Expression Parser."""')
    lines.append('from typing import Any, Dict, List, Optional, Union, Callable')
    lines.append('import re')
    lines.append('import math')
    lines.append('from enum import Enum')
    lines.append('')
    lines.append('class TokenType(Enum):')
    lines.append('    IDENTIFIER = "IDENTIFIER"')
    lines.append('    NUMBER = "NUMBER"')
    lines.append('    STRING = "STRING"')
    lines.append('    BOOLEAN = "BOOLEAN"')
    lines.append('    OPERATOR = "OPERATOR"')
    lines.append('    LPAREN = "LPAREN"')
    lines.append('    RPAREN = "RPAREN"')
    lines.append('    COMMA = "COMMA"')
    lines.append('    EOF = "EOF"')
    lines.append('')
    lines.append('class Token:')
    lines.append('    def __init__(self, type_: TokenType, value: Any, line: int = 1, col: int = 1):')
    lines.append('        self.type = type_')
    lines.append('        self.value = value')
    lines.append('        self.line = line')
    lines.append('        self.col = col')
    lines.append('    def __repr__(self):')
    lines.append('        return f"Token({self.type.name}, {self.value!r})"')
    lines.append('')
    lines.append('class ASTNode:')
    lines.append('    def evaluate(self, context: Dict[str, Any]) -> Any:')
    lines.append('        raise NotImplementedError')
    lines.append('')
    lines.append('class LiteralNode(ASTNode):')
    lines.append('    def __init__(self, value: Any):')
    lines.append('        self.value = value')
    lines.append('    def evaluate(self, context: Dict[str, Any]) -> Any:')
    lines.append('        return self.value')
    lines.append('')
    lines.append('class VariableNode(ASTNode):')
    lines.append('    def __init__(self, name: str):')
    lines.append('        self.name = name')
    lines.append('    def evaluate(self, context: Dict[str, Any]) -> Any:')
    lines.append('        parts = self.name.split(".")')
    lines.append('        cur = context')
    lines.append('        for p in parts:')
    lines.append('            if isinstance(cur, dict) and p in cur:')
    lines.append('                cur = cur[p]')
    lines.append('            elif hasattr(cur, p):')
    lines.append('                cur = getattr(cur, p)')
    lines.append('            else:')
    lines.append('                return None')
    lines.append('        return cur')
    lines.append('')
    lines.append('class BinaryOpNode(ASTNode):')
    lines.append('    def __init__(self, left: ASTNode, op: str, right: ASTNode):')
    lines.append('        self.left = left')
    lines.append('        self.op = op.upper()')
    lines.append('        self.right = right')
    lines.append('    def evaluate(self, context: Dict[str, Any]) -> Any:')
    lines.append('        l = self.left.evaluate(context)')
    lines.append('        r = self.right.evaluate(context)')
    lines.append('        if self.op == "==": return l == r')
    lines.append('        if self.op == "!=": return l != r')
    lines.append('        if self.op == "<": return (l or 0) < (r or 0)')
    lines.append('        if self.op == "<=": return (l or 0) <= (r or 0)')
    lines.append('        if self.op == ">": return (l or 0) > (r or 0)')
    lines.append('        if self.op == ">=": return (l or 0) >= (r or 0)')
    lines.append('        if self.op == "AND": return bool(l) and bool(r)')
    lines.append('        if self.op == "OR": return bool(l) or bool(r)')
    lines.append('        if self.op == "IN": return l in (r if isinstance(r, (list, tuple, set, str)) else [r])')
    lines.append('        if self.op == "NOT_IN": return l not in (r if isinstance(r, (list, tuple, set, str)) else [r])')
    lines.append('        if self.op == "CONTAINS": return (r in l) if (isinstance(l, (list, tuple, set, str)) and r is not None) else False')
    lines.append('        if self.op == "+": return (l or 0) + (r or 0)')
    lines.append('        if self.op == "-": return (l or 0) - (r or 0)')
    lines.append('        if self.op == "*": return (l or 0) * (r or 0)')
    lines.append('        if self.op == "/": return (l or 0) / (r or 1) if r != 0 else 0')
    lines.append('        return False')
    lines.append('')
    lines.append('class FunctionCallNode(ASTNode):')
    lines.append('    def __init__(self, func_name: str, args: List[ASTNode]):')
    lines.append('        self.func_name = func_name.upper()')
    lines.append('        self.args = args')
    lines.append('    def evaluate(self, context: Dict[str, Any]) -> Any:')
    lines.append('        evaluated_args = [a.evaluate(context) for a in self.args]')
    lines.append('        if self.func_name == "UPPER":')
    lines.append('            return str(evaluated_args[0]).upper() if evaluated_args else ""')
    lines.append('        if self.func_name == "LOWER":')
    lines.append('            return str(evaluated_args[0]).lower() if evaluated_args else ""')
    lines.append('        if self.func_name == "ABS":')
    lines.append('            return abs(float(evaluated_args[0])) if evaluated_args else 0.0')
    lines.append('        if self.func_name == "LEN":')
    lines.append('            return len(evaluated_args[0]) if evaluated_args and evaluated_args[0] is not None else 0')
    lines.append('        if self.func_name == "COALESCE":')
    lines.append('            for arg in evaluated_args:')
    lines.append('                if arg is not None:')
    lines.append('                    return arg')
    lines.append('            return None')
    lines.append('        if self.func_name == "ROUND":')
    lines.append('            digits = int(evaluated_args[1]) if len(evaluated_args) > 1 else 0')
    lines.append('            return round(float(evaluated_args[0]), digits) if evaluated_args else 0.0')
    lines.append('        if self.func_name == "STARTSWITH":')
    lines.append('            return str(evaluated_args[0]).startswith(str(evaluated_args[1])) if len(evaluated_args) >= 2 else False')
    lines.append('        if self.func_name == "ENDSWITH":')
    lines.append('            return str(evaluated_args[0]).endswith(str(evaluated_args[1])) if len(evaluated_args) >= 2 else False')
    lines.append('        return None')
    lines.append('')
    lines.append('class DSLTokenizer:')
    lines.append('    def __init__(self, text: str):')
    lines.append('        self.text = text')
    lines.append('        self.pos = 0')
    lines.append('        self.length = len(text)')
    lines.append('    def tokenize(self) -> List[Token]:')
    lines.append('        tokens = []')
    lines.append('        while self.pos < self.length:')
    lines.append('            ch = self.text[self.pos]')
    lines.append('            if ch.isspace():')
    lines.append('                self.pos += 1')
    lines.append('                continue')
    lines.append('            if ch == "(": tokens.append(Token(TokenType.LPAREN, "(")); self.pos += 1; continue')
    lines.append('            if ch == ")": tokens.append(Token(TokenType.RPAREN, ")")); self.pos += 1; continue')
    lines.append('            if ch == ",": tokens.append(Token(TokenType.COMMA, ",")); self.pos += 1; continue')
    lines.append('            if ch in ("\'", \'"\'):')
    lines.append('                quote = ch')
    lines.append('                self.pos += 1')
    lines.append('                start = self.pos')
    lines.append('                while self.pos < self.length and self.text[self.pos] != quote:')
    lines.append('                    if self.text[self.pos] == "\\\\" and self.pos + 1 < self.length:')
    lines.append('                        self.pos += 2')
    lines.append('                    else:')
    lines.append('                        self.pos += 1')
    lines.append('                val = self.text[start:self.pos]')
    lines.append('                self.pos += 1')
    lines.append('                tokens.append(Token(TokenType.STRING, val))')
    lines.append('                continue')
    lines.append('            if ch.isdigit() or (ch == "." and self.pos + 1 < self.length and self.text[self.pos+1].isdigit()):')
    lines.append('                start = self.pos')
    lines.append('                has_dot = False')
    lines.append('                while self.pos < self.length and (self.text[self.pos].isdigit() or (self.text[self.pos] == "." and not has_dot)):')
    lines.append('                    if self.text[self.pos] == ".": has_dot = True')
    lines.append('                    self.pos += 1')
    lines.append('                val_str = self.text[start:self.pos]')
    lines.append('                tokens.append(Token(TokenType.NUMBER, float(val_str) if has_dot else int(val_str)))')
    lines.append('                continue')
    lines.append('            for op in ("<=", ">=", "==", "!=", "AND", "OR", "NOT_IN", "IN", "CONTAINS", "<", ">", "+", "-", "*", "/"):')
    lines.append('                sub = self.text[self.pos:self.pos+len(op)]')
    lines.append('                if (op.isalpha() and sub.upper() == op and (self.pos+len(op) >= self.length or not self.text[self.pos+len(op)].isalnum())) or (not op.isalpha() and sub == op):')
    lines.append('                    tokens.append(Token(TokenType.OPERATOR, op))')
    lines.append('                    self.pos += len(op)')
    lines.append('                    break')
    lines.append('            else:')
    lines.append('                if ch.isalpha() or ch == "_":')
    lines.append('                    start = self.pos')
    lines.append('                    while self.pos < self.length and (self.text[self.pos].isalnum() or self.text[self.pos] in ("_", ".")):')
    lines.append('                        self.pos += 1')
    lines.append('                    ident = self.text[start:self.pos]')
    lines.append('                    if ident.upper() in ("TRUE", "FALSE"):')
    lines.append('                        tokens.append(Token(TokenType.BOOLEAN, ident.upper() == "TRUE"))')
    lines.append('                    else:')
    lines.append('                        tokens.append(Token(TokenType.IDENTIFIER, ident))')
    lines.append('                else:')
    lines.append('                    self.pos += 1')
    lines.append('        tokens.append(Token(TokenType.EOF, None))')
    lines.append('        return tokens')
    lines.append('')
    lines.append('class DSLParser:')
    lines.append('    def __init__(self, tokens: List[Token]):')
    lines.append('        self.tokens = tokens')
    lines.append('        self.idx = 0')
    lines.append('    def current(self) -> Token:')
    lines.append('        return self.tokens[self.idx] if self.idx < len(self.tokens) else self.tokens[-1]')
    lines.append('    def eat(self, type_: Optional[TokenType] = None, val: Any = None) -> Token:')
    lines.append('        tok = self.current()')
    lines.append('        if type_ and tok.type != type_:')
    lines.append('            raise SyntaxError(f"Expected token type {type_}, found {tok}")')
    lines.append('        if val and str(tok.value).upper() != str(val).upper():')
    lines.append('            raise SyntaxError(f"Expected value {val}, found {tok.value}")')
    lines.append('        self.idx += 1')
    lines.append('        return tok')
    lines.append('    def parse(self) -> ASTNode:')
    lines.append('        res = self.parse_or()')
    lines.append('        return res')
    lines.append('    def parse_or(self) -> ASTNode:')
    lines.append('        node = self.parse_and()')
    lines.append('        while self.current().type == TokenType.OPERATOR and str(self.current().value).upper() == "OR":')
    lines.append('            op = self.eat().value')
    lines.append('            right = self.parse_and()')
    lines.append('            node = BinaryOpNode(node, op, right)')
    lines.append('        return node')
    lines.append('    def parse_and(self) -> ASTNode:')
    lines.append('        node = self.parse_comparison()')
    lines.append('        while self.current().type == TokenType.OPERATOR and str(self.current().value).upper() == "AND":')
    lines.append('            op = self.eat().value')
    lines.append('            right = self.parse_comparison()')
    lines.append('            node = BinaryOpNode(node, op, right)')
    lines.append('        return node')
    lines.append('    def parse_comparison(self) -> ASTNode:')
    lines.append('        node = self.parse_additive()')
    lines.append('        cmp_ops = ("==", "!=", "<", "<=", ">", ">=", "IN", "NOT_IN", "CONTAINS")')
    lines.append('        while self.current().type == TokenType.OPERATOR and str(self.current().value).upper() in cmp_ops:')
    lines.append('            op = self.eat().value')
    lines.append('            right = self.parse_additive()')
    lines.append('            node = BinaryOpNode(node, op, right)')
    lines.append('        return node')
    lines.append('    def parse_additive(self) -> ASTNode:')
    lines.append('        node = self.parse_multiplicative()')
    lines.append('        while self.current().type == TokenType.OPERATOR and str(self.current().value) in ("+", "-"):')
    lines.append('            op = self.eat().value')
    lines.append('            right = self.parse_multiplicative()')
    lines.append('            node = BinaryOpNode(node, op, right)')
    lines.append('        return node')
    lines.append('    def parse_multiplicative(self) -> ASTNode:')
    lines.append('        node = self.parse_primary()')
    lines.append('        while self.current().type == TokenType.OPERATOR and str(self.current().value) in ("*", "/"):')
    lines.append('            op = self.eat().value')
    lines.append('            right = self.parse_primary()')
    lines.append('            node = BinaryOpNode(node, op, right)')
    lines.append('        return node')
    lines.append('    def parse_primary(self) -> ASTNode:')
    lines.append('        tok = self.current()')
    lines.append('        if tok.type == TokenType.NUMBER:')
    lines.append('            self.eat()')
    lines.append('            return LiteralNode(tok.value)')
    lines.append('        if tok.type == TokenType.STRING:')
    lines.append('            self.eat()')
    lines.append('            return LiteralNode(tok.value)')
    lines.append('        if tok.type == TokenType.BOOLEAN:')
    lines.append('            self.eat()')
    lines.append('            return LiteralNode(tok.value)')
    lines.append('        if tok.type == TokenType.LPAREN:')
    lines.append('            self.eat(TokenType.LPAREN)')
    lines.append('            sub = self.parse_or()')
    lines.append('            self.eat(TokenType.RPAREN)')
    lines.append('            return sub')
    lines.append('        if tok.type == TokenType.IDENTIFIER:')
    lines.append('            name = self.eat().value')
    lines.append('            if self.current().type == TokenType.LPAREN:')
    lines.append('                self.eat(TokenType.LPAREN)')
    lines.append('                args = []')
    lines.append('                if self.current().type != TokenType.RPAREN:')
    lines.append('                    args.append(self.parse_or())')
    lines.append('                    while self.current().type == TokenType.COMMA:')
    lines.append('                        self.eat(TokenType.COMMA)')
    lines.append('                        args.append(self.parse_or())')
    lines.append('                self.eat(TokenType.RPAREN)')
    lines.append('                return FunctionCallNode(name, args)')
    lines.append('            return VariableNode(name)')
    lines.append('        raise SyntaxError(f"Unexpected token in expression: {tok}")')
    lines.append('')
    lines.append('def compile_rule_expression(expr_str: str) -> ASTNode:')
    lines.append('    tokenizer = DSLTokenizer(expr_str)')
    lines.append('    tokens = tokenizer.tokenize()')
    lines.append('    parser = DSLParser(tokens)')
    lines.append('    return parser.parse()')
    lines.append('')
    lines.append('def evaluate_rule(expr_str: str, context: Dict[str, Any]) -> bool:')
    lines.append('    ast = compile_rule_expression(expr_str)')
    lines.append('    res = ast.evaluate(context)')
    lines.append('    return bool(res)')
    lines.append('')
    return '\n'.join(lines)

print("[+] Script ready to generate rule DSL")
